/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package endor.java.gradle8.kotlin.script;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
